# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'main_UI.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1366, 768)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.stackedWidget = QtWidgets.QStackedWidget(self.centralwidget)
        self.stackedWidget.setGeometry(QtCore.QRect(174, 11, 1181, 721))
        self.stackedWidget.setStyleSheet("")
        self.stackedWidget.setObjectName("stackedWidget")
        self.page_1 = QtWidgets.QWidget()
        self.page_1.setObjectName("page_1")
        self.label = QtWidgets.QLabel(self.page_1)
        self.label.setGeometry(QtCore.QRect(230, 520, 72, 15))
        self.label.setObjectName("label")
        self.tableView = QtWidgets.QTableView(self.page_1)
        self.tableView.setGeometry(QtCore.QRect(620, 300, 256, 192))
        self.tableView.setObjectName("tableView")
        self.stackedWidget.addWidget(self.page_1)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.stackedWidget.addWidget(self.page_2)
        self.page_3 = QtWidgets.QWidget()
        self.page_3.setObjectName("page_3")
        self.stackedWidget.addWidget(self.page_3)
        self.menuBtn_1 = QtWidgets.QPushButton(self.centralwidget)
        self.menuBtn_1.setGeometry(QtCore.QRect(20, 70, 141, 61))
        self.menuBtn_1.setObjectName("menuBtn_1")
        self.menuBtn_2 = QtWidgets.QPushButton(self.centralwidget)
        self.menuBtn_2.setGeometry(QtCore.QRect(20, 170, 141, 61))
        self.menuBtn_2.setObjectName("menuBtn_2")
        self.menuBtn_3 = QtWidgets.QPushButton(self.centralwidget)
        self.menuBtn_3.setGeometry(QtCore.QRect(20, 270, 141, 61))
        self.menuBtn_3.setObjectName("menuBtn_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.menuBtn_1.setText(_translate("MainWindow", "第一页"))
        self.menuBtn_2.setText(_translate("MainWindow", "第二页"))
        self.menuBtn_3.setText(_translate("MainWindow", "第三页"))
