# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_3.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_page_3(object):
    def setupUi(self, page_3):
        page_3.setObjectName("page_3")
        page_3.resize(1146, 716)
        self.tableView = QtWidgets.QTableView(page_3)
        self.tableView.setGeometry(QtCore.QRect(10, 80, 1150, 491))
        self.tableView.setObjectName("tableView")
        self.label = QtWidgets.QLabel(page_3)
        self.label.setGeometry(QtCore.QRect(430, 80, 72, 16))
        self.label.setObjectName("label")
        self.select_Edit = QtWidgets.QLineEdit(page_3)
        self.select_Edit.setGeometry(QtCore.QRect(82, 610, 141, 30))
        self.select_Edit.setObjectName("select_Edit")
        self.select_Btn = QtWidgets.QPushButton(page_3)
        self.select_Btn.setGeometry(QtCore.QRect(300, 610, 93, 30))
        self.select_Btn.setObjectName("select_Btn")
        self.refresh_Btn = QtWidgets.QPushButton(page_3)
        self.refresh_Btn.setGeometry(QtCore.QRect(490, 610, 93, 30))
        self.refresh_Btn.setObjectName("refresh_Btn")

        self.retranslateUi(page_3)
        QtCore.QMetaObject.connectSlotsByName(page_3)

    def retranslateUi(self, page_3):
        _translate = QtCore.QCoreApplication.translate
        page_3.setWindowTitle(_translate("page_3", "Form"))
        self.label.setText(_translate("page_3", "3"))
        self.select_Edit.setPlaceholderText(_translate("page_3", "工号/姓名"))
        self.select_Btn.setText(_translate("page_3", "查询"))
        self.refresh_Btn.setText(_translate("page_3", "刷新"))
