# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'page_1.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets
from PyQt5.QtWidgets import QWidget


class Ui_page_1(QWidget):
    def __init__(self,parent):
        super().__init__(parent=parent)
        self.setupUi(self)
    def setupUi(self, page_1):
        page_1.setObjectName("page_1")
        page_1.resize(908, 583)
        self.pushButton = QtWidgets.QPushButton(page_1)
        self.pushButton.setGeometry(QtCore.QRect(560, 60, 301, 171))
        self.pushButton.setObjectName("pushButton")
        self.label = QtWidgets.QLabel(page_1)
        self.label.setGeometry(QtCore.QRect(100, 140, 421, 391))
        self.label.setObjectName("label")

        self.retranslateUi(page_1)
        QtCore.QMetaObject.connectSlotsByName(page_1)

    def retranslateUi(self, page_1):
        _translate = QtCore.QCoreApplication.translate
        page_1.setWindowTitle(_translate("page_1", "Form"))
        self.pushButton.setText(_translate("page_1", "PushButton"))
        self.label.setText(_translate("page_1", "TextLabel"))
